import { notFound } from "next/navigation";

import { DisclosureBanner } from "@/components/disclosure-banner";
import { getProfilePreviewByToken } from "@/lib/server/inveniam";

export default async function PlayerPublicPage({
  params
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const profile = await getProfilePreviewByToken(token);

  if (!profile) {
    notFound();
  }

  return (
    <div className="page-stack">
      <section className="panel hero-panel">
        <div className="page-header">
          <p className="eyebrow">Controlled player preview</p>
          <h1>{profile.displayName ?? "Inveniam Sport player"}</h1>
          <p>
            This dossier is a shareable preview generated by the platform to help clubs
            and stakeholders evaluate fit without exposing private contact details.
          </p>
        </div>
        <DisclosureBanner />
      </section>

      <section className="two-column dossier-grid">
        <article className="panel">
          <div className="detail-grid">
            <div>
              <span className="meta-label">Primary position</span>
              <strong>{profile.primaryPosition ?? "Not provided"}</strong>
            </div>
            <div>
              <span className="meta-label">Secondary positions</span>
              <strong>{profile.secondaryPositions.join(", ") || "Not provided"}</strong>
            </div>
            <div>
              <span className="meta-label">Age band</span>
              <strong>{profile.ageBand ?? "Not provided"}</strong>
            </div>
            <div>
              <span className="meta-label">Nationality</span>
              <strong>{profile.nationality ?? "Not provided"}</strong>
            </div>
            <div>
              <span className="meta-label">Availability</span>
              <strong>{profile.availability ?? "Not provided"}</strong>
            </div>
            <div>
              <span className="meta-label">Work authorization</span>
              <strong>{profile.workAuthorization ?? "Not provided"}</strong>
            </div>
          </div>
          <div className="progress-shell" aria-hidden="true">
            <div className="progress-bar" style={{ width: `${profile.completenessScore}%` }} />
          </div>
          <p className="meta-note">Completeness score: {profile.completenessScore}%</p>
        </article>

        <article className="panel">
          <h2>Bio</h2>
          <p>{profile.bio ?? "No bio provided yet."}</p>
          <div className="stack-list">
            {profile.mediaAssets.map((asset) => (
              <div className="list-card" key={asset.id}>
                <strong>
                  {typeof asset.metadataJson === "object" && asset.metadataJson && "label" in asset.metadataJson
                    ? String((asset.metadataJson as { label?: string }).label ?? asset.assetType)
                    : asset.assetType}
                </strong>
                {asset.externalUrl ? <p className="meta-note">{asset.externalUrl}</p> : null}
                {asset.storagePath ? <p className="meta-note">{asset.storagePath}</p> : null}
              </div>
            ))}
          </div>
        </article>
      </section>
    </div>
  );
}
